//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phacmarcity_ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuXuat
    {
        public string MaPX { get; set; }
        public string MaThuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual Thuoc Thuoc { get; set; }
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual PhieuXuat PhieuXuat1 { get; set; }
        public virtual Thuoc Thuoc1 { get; set; }
    }
}
